# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'action.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiAction(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 395)
        self.info_label = QtWidgets.QLabel(Form)
        self.info_label.setGeometry(QtCore.QRect(10, 10, 381, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.info_label.setFont(font)
        self.info_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 100, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.line_log = QtWidgets.QLineEdit(Form)
        self.line_log.setGeometry(QtCore.QRect(60, 130, 281, 20))
        self.line_log.setObjectName("line_log")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 160, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line_pas = QtWidgets.QLineEdit(Form)
        self.line_pas.setGeometry(QtCore.QRect(60, 190, 281, 20))
        self.line_pas.setObjectName("line_pas")
        self.actoin_btn = QtWidgets.QPushButton(Form)
        self.actoin_btn.setGeometry(QtCore.QRect(140, 220, 121, 23))
        self.actoin_btn.setText("")
        self.actoin_btn.setObjectName("actoin_btn")
        self.result_lab = QtWidgets.QLabel(Form)
        self.result_lab.setGeometry(QtCore.QRect(20, 249, 361, 41))
        self.result_lab.setText("")
        self.result_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.result_lab.setWordWrap(True)
        self.result_lab.setObjectName("result_lab")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 300, 361, 81))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Логин"))
        self.label_2.setText(_translate("Form", "Пароль"))
        self.label_3.setText(_translate("Form", "Длина пароля больше 8 символов.\n"
"В нем присутствуют большие и маленькие буквы любого алфавита.\n"
"В нем имеется хотя бы одна цифра.\n"
"В пароле нет ни одной комбинации из 3 буквенных символов, стоящих рядом в строке клавиатуры независимо от того, русская раскладка выбрана или английская"))
