# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choice.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiChoice(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(452, 275)
        font = QtGui.QFont()
        font.setPointSize(13)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 431, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.num_8a = QtWidgets.QPushButton(self.centralwidget)
        self.num_8a.setGeometry(QtCore.QRect(10, 200, 431, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_8a.sizePolicy().hasHeightForWidth())
        self.num_8a.setSizePolicy(sizePolicy)
        self.num_8a.setObjectName("num_8a")
        self.num_7_1 = QtWidgets.QPushButton(self.centralwidget)
        self.num_7_1.setGeometry(QtCore.QRect(10, 80, 431, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_7_1.sizePolicy().hasHeightForWidth())
        self.num_7_1.setSizePolicy(sizePolicy)
        self.num_7_1.setObjectName("num_7_1")
        self.num_7_2 = QtWidgets.QPushButton(self.centralwidget)
        self.num_7_2.setGeometry(QtCore.QRect(10, 140, 431, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_7_2.sizePolicy().hasHeightForWidth())
        self.num_7_2.setSizePolicy(sizePolicy)
        self.num_7_2.setObjectName("num_7_2")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Тренажёр"))
        self.label.setText(_translate("mainWindow", "Выберите задание"))
        self.num_8a.setText(_translate("mainWindow", "8a :Слова в алфавитном порядке"))
        self.num_7_1.setText(_translate("mainWindow", "7 - Кодирование изображений"))
        self.num_7_2.setText(_translate("mainWindow", "7-2 - Кодирование звука"))
