# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiEnter(object):
    def setupUi(self, Enter):
        Enter.setObjectName("Enter")
        Enter.resize(401, 290)
        self.info_label = QtWidgets.QLabel(Enter)
        self.info_label.setGeometry(QtCore.QRect(30, 10, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info_label.setFont(font)
        self.info_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setObjectName("info_label")
        self.splitter = QtWidgets.QSplitter(Enter)
        self.splitter.setGeometry(QtCore.QRect(50, 110, 301, 101))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.btn_singin = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_singin.setFont(font)
        self.btn_singin.setObjectName("btn_singin")
        self.btn_singup = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_singup.setFont(font)
        self.btn_singup.setObjectName("btn_singup")
        self.anonim = QtWidgets.QPushButton(Enter)
        self.anonim.setGeometry(QtCore.QRect(50, 222, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.anonim.setFont(font)
        self.anonim.setObjectName("anonim")

        self.retranslateUi(Enter)
        QtCore.QMetaObject.connectSlotsByName(Enter)

    def retranslateUi(self, Enter):
        _translate = QtCore.QCoreApplication.translate
        Enter.setWindowTitle(_translate("Enter", "Вход/Регистрация"))
        self.info_label.setText(_translate("Enter", "Тренажёр по заданиям ЕГЭ по информатике"))
        self.btn_singin.setText(_translate("Enter", "Вход"))
        self.btn_singup.setText(_translate("Enter", "Регистрация"))
        self.anonim.setText(_translate("Enter", "Анонимный вход"))
